# Site settings
title: Kurippu
email: your-email@domain.com
description: "Just some notes"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: ananth
github_username:  ananthp

# Build settings
markdown: kramdown
permalink: pretty
