# Site settings
title: Kurippu
email: your-email@domain.com
description: "Notes on customizing linux, windows, common fixes and a bit more."
baseurl: "/kurippu"
url: "http://yourdomain.com"
twitter_username: rpattabi
github_username:  rpattabi

# Build settings
markdown: kramdown
permalink: pretty

categories: navigation

gems:
 - jekyll-redirect-from
